export default [
    {
      "_id": "A101",
      "title": "Propulsion Assignment",
      "course": "RS101",
      "not_available_until": "May 6 at 12:00am",
      "due": "May 13 at 11:59pm",
      "startDate": "2023-05-06",
      "endDate": "2023-05-13",
      "dueDate": "2023-05-13",
      "points": "100",
      "description": "The assignment is available online. Submit a link to the landing page of your Web application running on Netlify. The landing page should include the following: Your full name and section Links to each of the lab assignments Link to the Kanbas application Links to all relevant source code repositories The Kanbas application should include a link to navigate back to the landing page."
    },
    {
      "_id": "A102",
      "title": "Combustion Analysis",
      "course": "RS101",
      "not_available_until": "May 13 at 12:00am",
      "due": "May 20 at 11:59pm",
      "startDate": "2023-05-13",
      "endDate": "2023-05-20",
      "dueDate": "2023-05-20",
      "points": "100",
      "description": "The assignment is available online. Submit a link to the landing page of your Web application running on Netlify. The landing page should include the following: Your full name and section Links to each of the lab assignments Link to the Kanbas application Links to all relevant source code repositories The Kanbas application should include a link to navigate back to the landing page."
    },
    {
      "_id": "A103",
      "title": "Nozzle Design Project",
      "course": "RS101",
      "not_available_until": "May 20 at 12:00am",
      "due": "May 27 at 11:59pm",
      "startDate": "2023-05-20",
      "endDate": "2023-05-27",
      "dueDate": "2023-05-27",
      "points": "100",
      "description": "The assignment is available online. Submit a link to the landing page of your Web application running on Netlify. The landing page should include the following: Your full name and section Links to each of the lab assignments Link to the Kanbas application Links to all relevant source code repositories The Kanbas application should include a link to navigate back to the landing page."
    },
    {
      "_id": "A201",
      "title": "Aerodynamics Quiz",
      "course": "RS102",
      "not_available_until": "May 6 at 12:00am",
      "due": "May 13 at 11:59pm",
      "startDate": "2023-05-06",
      "endDate": "2023-05-13",
      "dueDate": "2023-05-13",
      "points": "100",
      "description": "The assignment is available online. Submit a link to the landing page of your Web application running on Netlify. The landing page should include the following: Your full name and section Links to each of the lab assignments Link to the Kanbas application Links to all relevant source code repositories The Kanbas application should include a link to navigate back to the landing page."
    },
    {
      "_id": "A202",
      "title": "Flow Analysis",
      "course": "RS102",
      "not_available_until": "May 13 at 12:00am",
      "due": "May 20 at 11:59pm",
      "startDate": "2023-05-13",
      "endDate": "2023-05-20",
      "dueDate": "2023-05-20",
      "points": "100",
      "description": "The assignment is available online. Submit a link to the landing page of your Web application running on Netlify. The landing page should include the following: Your full name and section Links to each of the lab assignments Link to the Kanbas application Links to all relevant source code repositories The Kanbas application should include a link to navigate back to the landing page."
    },
    {
      "_id": "A203",
      "title": "Heating Analysis",
      "course": "RS102",
      "not_available_until": "May 20 at 12:00am",
      "due": "May 27 at 11:59pm",
      "startDate": "2023-05-20",
      "endDate": "2023-05-27",
      "dueDate": "2023-05-27",
      "points": "100",
      "description": "The assignment is available online. Submit a link to the landing page of your Web application running on Netlify. The landing page should include the following: Your full name and section Links to each of the lab assignments Link to the Kanbas application Links to all relevant source code repositories The Kanbas application should include a link to navigate back to the landing page."
    },
    {
      "_id": "A301",
      "title": "Structural Design Task",
      "course": "RS103",
      "not_available_until": "May 6 at 12:00am",
      "due": "May 13 at 11:59pm",
      "startDate": "2023-05-06",
      "endDate": "2023-05-13",
      "dueDate": "2023-05-13",
      "points": "100",
      "description": "The assignment is available online. Submit a link to the landing page of your Web application running on Netlify. The landing page should include the following: Your full name and section Links to each of the lab assignments Link to the Kanbas application Links to all relevant source code repositories The Kanbas application should include a link to navigate back to the landing page."
    },
    {
      "_id": "A302",
      "title": "Orbital Calculations",
      "course": "RS103",
      "not_available_until": "May 13 at 12:00am",
      "due": "May 20 at 11:59pm",
      "startDate": "2023-05-13",
      "endDate": "2023-05-20",
      "dueDate": "2023-05-20",
      "points": "100",
      "description": "The assignment is available online. Submit a link to the landing page of your Web application running on Netlify. The landing page should include the following: Your full name and section Links to each of the lab assignments Link to the Kanbas application Links to all relevant source code repositories The Kanbas application should include a link to navigate back to the landing page."
    },
    {
      "_id": "A303",
      "title": "Systems Engineering Exam",
      "course": "RS103",
      "not_available_until": "May 20 at 12:00am",
      "due": "May 27 at 11:59pm",
      "startDate": "2023-05-20",
      "endDate": "2023-05-27",
      "dueDate": "2023-05-27",
      "points": "100",
      "description": "The assignment is available online. Submit a link to the landing page of your Web application running on Netlify. The landing page should include the following: Your full name and section Links to each of the lab assignments Link to the Kanbas application Links to all relevant source code repositories The Kanbas application should include a link to navigate back to the landing page."
    }
]